In [26]:


# importing necessary libraries
import numpy as np 
import re

In [27]:
#defining the necessary feautres


In [28]:
positive_reviews = { "incredible" , "engaging", "loved", "stunning" , "perfectly" , "goodness" , "heart" , "amazing" , "great", "fantastic"}
negative_reviews = { "letdown" , "didn't" , "cheesy","cringe" , "fake" , "worse","bad","terrible" , "sucks","boring"}
pronouns = {"he", "she", "i", "we","you","they","it"}
                     
                    

                

In [29]:
#defining the function to extract the features

In [30]:
import re
def extract_features(sentence):
  pos_sum = 0 
  neg_sum = 0 
  pronoun_count = 0
  
  words = re.findall(r'\b\w+\b', sentence.lower()) 
  positive_count = sum(1 for word in words if word in positive_reviews)
  negative_count = sum(1 for word in words if word in negative_reviews)
  pronoun_count = sum(1 for word in words if word in pronouns)
  if "?" in sentence or "!" in sentence:
     has_punctuation = 1 
  else:
    has_punctuation = 0
  word_count = len(words)
  return np.array([positive_count , negative_count, pronoun_count , has_punctuation,word_count]) 


         


In [31]:
review1 = "Wow, that movie was incredible! The storytelling was so engaging, and the characters felt so real. I loved how the plot twists kept me on the edge of my seat. The cinematography was stunning, especially the way they used lighting to set the mood. And the soundtrack—oh my goodness, it perfectly complemented every scene! Honestly, I can’t stop thinking about it; I’d watch it again in a heartbeat."
review2 = "Ugh, that movie was such a letdown. The plot was all over the place, and the characters didn’t make any sense. Half the time, I couldn’t figure out what was happening or why I was supposed to care. The dialogue was so cheesy, it made me cringe, and don’t get me started on the special effects—they looked super fake! I kept checking my watch, hoping it would end soon. Honestly, I wouldn’t recommend it to anyone."


In [32]:
#utilizing gradient descent to identify weights and bias

In [33]:


# Features and labels
X = np.array([
    [6, 0, 7, 1, 71],  # Review 1 features
    [0, 4, 8, 1, 81]   # Review 2 features
])
Y = np.array([1, 0])  # Labels: 1 for positive, 0 for negative

# Initialize weights and bias randomly
weights = np.random.rand(X.shape[1])  # One weight per feature
bias = np.random.rand()


# Sigmoid function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Gradient Descent parameters
learning_rate = 0.01
num_epochs = 1000

# Training loop
for epoch in range(num_epochs):
    # Step 1: Calculate linear combination (z) and predictions
    z = np.dot(X, weights) + bias
    predictions = sigmoid(z)
    epsilon = 1e-15  # Small value to avoid numerical issues
    predictions = np.clip(predictions, epsilon, 1 - epsilon)

# Recalculate loss
    loss = -np.mean(Y * np.log(predictions) + (1 - Y) * np.log(1 - predictions))


    # Step 3: Calculate gradients for weights and bias
    dw = np.dot(X.T, (predictions - Y)) / len(Y)  # Gradient for weights
    db = np.sum(predictions - Y) / len(Y)         # Gradient for bias

    # Step 4: Update weights and bias
    weights -= learning_rate * dw
    bias -= learning_rate * db

    # Print loss every 100 epochs
    if epoch % 100 == 0:
        print(f"Epoch {epoch}, Loss: {loss:.4f}")

# Final trained weights and bias
print("Trained Weights:", weights)
print("Trained Bias:", bias)



[0.90565049 0.27539388 0.05909744 0.5105169  0.91527995]
0.711541551388364
Epoch 0, Loss: 17.2698
Epoch 100, Loss: 0.4745
Epoch 200, Loss: 0.0002
Epoch 300, Loss: 0.0001
Epoch 400, Loss: 0.0001
Epoch 500, Loss: 0.0001
Epoch 600, Loss: 0.0001
Epoch 700, Loss: 0.0001
Epoch 800, Loss: 0.0001
Epoch 900, Loss: 0.0001
Trained Weights: [ 2.45141487 -0.67763318 -0.04356491  0.52988754 -0.0919729 ]
Trained Bias: 0.7309121824007024


In [34]:
#defining the threshold value to classify

In [35]:
threshold_value = 0.5 
def threshold(value):
           if value > threshold_value:
                  print("Positive")
           else:
                 print("Negative")

In [36]:
x = extract_features(review1)
print(x)
z = np.dot(weights, x) + bias
print(z)
value = sigmoid(z)
threshold(value)

[ 6  0  7  1 71]
9.134258522439325
Positive


In [44]:
x1 = extract_features(review2)
print(x1)
z = np.dot(weights, x1) + bias
print(z)
value = sigmoid(z)
threshold(value)

[ 0  4  8  1 81]
-9.24805735281168
Negative


In [38]:
#p = (0.69098014, 0.1126213 , 0.44850026 ,0.42306404, 0.06809109)*( 6.0 , 0.0 , 7.0 , 1.0,71.0)+0.5978427179592303

In [55]:
import numpy as np

# Sigmoid function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Input features for positive and negative feedback
positive_feedback = np.array( [ 6,  0,  7 , 1 ,71]) # Positive feedback
negative_feedback = np.array([0, 4, 8, 1, 81])  # Negative feedback

# Weights provided
weights = np.array([2.45141487, -0.67763318, -0.04356491, 0.52988754, -0.0919729])

# Adjusted bias value to align with positive/negative feedback
bias = -5.0  # Adjusting bias for correct output (lower bias for high P(1|x) in negative feedback)

# Function to compute z and probabilities
z = np.dot(weights,positive_feedback) + bias
z1 = np.dot(weights,negative_feedback) + bias


p_1_given_x = sigmoid(z)
p_0_given_x = 1 - p_1_given_x
p_1_given_x1 = sigmoid(z1)
p_0_given_x1 = 1 - p_1_given_x1
print(p_1_given_x )
print(p_0_given_x)
print(p_1_given_x1 )
print(p_0_given_x1)
    
    



0.9678089578357247
0.03219104216427526
3.124036696522586e-07
0.9999996875963304


In [ ]:
trying for some different bias values

In [56]:
import numpy as np

# Sigmoid function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Input features for positive and negative feedback
positive_feedback = np.array( [ 6,  0,  7 , 1 ,71]) # Positive feedback
negative_feedback = np.array([0, 4, 8, 1, 81])  # Negative feedback

# Weights provided
weights = np.array([2.45141487, -0.67763318, -0.04356491, 0.52988754, -0.0919729])

# Adjusted bias value to align with positive/negative feedback
bias =  0.7309121824007024 

# Function to compute z and probabilities
z = np.dot(weights,positive_feedback) + bias
z1 = np.dot(weights,negative_feedback) + bias


p_1_given_x = sigmoid(z)
p_0_given_x = 1 - p_1_given_x
p_1_given_x1 = sigmoid(z1)
p_0_given_x1 = 1 - p_1_given_x1
print(p_1_given_x )
print(p_0_given_x)
print(p_1_given_x1 )
print(p_0_given_x1)
    
    

0.9998921065693942
0.00010789343060579881
9.628928891905453e-05
0.999903710711081


In [ ]:
prediction of probability is more when bias = 0.7309121824007024 